### ISSUE TITLE
Importing two folders with the same name from an OPML file should merge their feeds

### ISSUE THREAD

**Issue by kuba-orlik** [owncloud/news#962]
# IMPORTANT

* [x] I have read the [CONTRIBUTING.md](https://github.com/owncloud/news/blob/master/CONTRIBUTING.md) and followed the provided tips

## Explain the Problem
I've imported OPML data from my feedly account and all of the feeds have been successfully imported. Unfortunately the app does not fetch any articles for any of the feeds (the unread list is consistently empty). I've ensured that the cron task is set up properly and I even tried running the `cron.php` and `updater.php` script manually, but no articles are fetched :(

## Steps to Reproduce
Explain what you did to encounter the issue
1. Import OPML file to a freshly installed News app
2. Wait few hours
3. No articles are fetched

## System Information
* News app version: 8.1.0
* ownCloud version: 9.0.0
* PHP version: 5.6-apache
* Database and version: SQLlite
* Browser and version: all browsers
* Distribution and version: Ubuntu 14.04.3 LTS

## Contents of owncloud/data/owncloud.log

No new entries in log after running cron task

## Contents of Browser Error Console
Doesn't apply

**Comment by BernhardPosselt** [comment]
Works for me, how did configure the cron? Also what happens if you run 

    sudo -u www-data php -f owncloud/cron.php  # may differ from www-data depending on distro

and can you paste your ini in owncloud/data/news/config/config.ini

**Comment by BernhardPosselt** [comment]
I've added a few more debugging tips here https://github.com/owncloud/news#feeds-are-not-updated

**Comment by kuba-orlik** [comment]
I've performed all these checks. The updater script *is* executed, but feeds are not refreshed. What other things should I look into?

**Comment by BernhardPosselt** [comment]
Can you paste your config.ini?

**Comment by BernhardPosselt** [comment]
Also can you curl the added feed from your console?

**Comment by BernhardPosselt** [comment]
Any news?

**Comment by kuba-orlik** [comment]
Hi, I just realized the issue was somewhere else - when importing the feeds from the OPML file, the app imported only the folders, without any feeds, without an error message - I assumed the feeds will show up once there are some new articles in them. My bad for not noticing that!

The error while importing the OPML file was due to there being two folders of that same name.

**Comment by BernhardPosselt** [comment]
two folders in the opml use the same name?

**Comment by kuba-orlik** [comment]
Yes, I exported it from Feedly. Apparently Feedly allows for two folders to have the same name. 

I've noticed an additional problem with the OPML import - if the OPML contains a folder bearing a name of an already existing one, the import will fail.

**Comment by BernhardPosselt** [comment]
Ok, should be merged then :)

**Comment by BernhardPosselt** [comment]
Should be fixed in master now, can you test?

**Comment by kuba-orlik** [comment]
I removed the `apps/news` directory, downloaded the release `tar.gz` of the `8.3.0` version and tried the `opml` file on a new account, and the issue still persists. One of the server's responses while importing is 

    `409: Can not add folder: Exists already`
